@startuml "Тёплый дом" - Контекстная диаграмма (As-Is)

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title Диаграмма контекста: Компания «Тёплый дом» (As-Is)

Person(people, "Владелец дома", "Управляет температурой в своем доме")

System_Boundary(sys1, "Компания «Тёплый дом»") {
    System(smartVillages, "Монолитная централизованная платформа", "Управление стройствами")
}

System_Ext(device, "Устройства в домах", "Оборудование (существующее и новое): \n• Датчики температуры \n• Дополнительные устройства")
'System_Ext(weather, "Сервис погоды", "Внешний источник данных для алгоритмов управления отоплением")

' Основные связи
Rel(people, smartVillages, "Управление устройствами через", "Мобильное приложение / Web")


' Связи с внешними системами
Rel(smartVillages, device, "Управляет и собирает данные", "MQTT/HTTPS/Протоколы IoT")
'Rel(smartVillages, weather, "Запроc прогноза погоды", "REST API")

' Аннотация с важным замечанием
note right of device
  <b>Ключевая проблема:</b>
  Оборудование установлено
  только в 50% домов
  желающих подключиться
end note


@enduml